### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by yatsurama** [DQiaole/ZITS_inpainting#14]
Hello,

thanks a lot for your great work!

When I run the single image test:

```
conda activate wireframes_inference_env
python single_image_test.py --path <ckpt_path> --config_file <config_path> \
 --GPU_ids '0' --img_path ./image.png --mask_path ./mask.png --save_path ./
```

I get an error 
`FileNotFoundError: [Errno 2] No such file or directory: '/home/wmlce/places365_standard/places2_all/train_list.txt'`

It is triggered when `single_image_test.py` is executing `model = ZITS(config, 0, 0, True)`. This path is defined in the config files. Can the script be run without this file?

Thank you!

**Comment by DQiaole** [comment]
Hi~
You are right! This path is defined for training set, you can run the script without this file, and I add a conditional branch when test:
https://github.com/DQiaole/ZITS_inpainting/blob/ac3259b32ef1938082d79561240e2fe49959f9a3/src/FTR_trainer.py#L271-L288

**Comment by yatsurama** [comment]
Thanks a lot for your very quick response! It works now. I am closing the issue.
