### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch==1.3.1

### ISSUE THREAD

**Issue by naoki7090624** [DQiaole/ZITS_inpainting#15]
Hi,
You recommend to inference the wireframes with torch 1.3.1 on README, but could not find the version by pip.
```
ERROR: Could not find a version that satisfies the requirement torch==1.3.1 (from versions: 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for torch==1.3.1
```
How did you install the old version?

**Comment by ewrfcas** [comment]
Hi, pytorch 1.3.1 is not available in python3.8, you can try to use 3.7 or 3.6.
Besides, this issue has been discussed in https://github.com/cherubicXN/hawp/issues/31, and the only way is to retrain the model in a new pytorch environment.
I am not sure if pytorch1.4 or 1.5 works properly in it. You can try other versions which are earlier than 1.9.

**Comment by naoki7090624** [comment]
Thank you for helping.
I tried using python 3.6.9 and 3.6.13, but torch 1.3.1 is not found yet.
```
(wireframes_inference_env) PS C:\Users\Naoki> python --version
Python 3.6.9 :: Anaconda, Inc.
(wireframes_inference_env) PS C:\Users\Naoki> pip install torch==1.3.1 torchvision==0.4.2
ERROR: Could not find a version that satisfies the requirement torch==1.3.1 (from versions: 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2)
ERROR: No matching distribution found for torch==1.3.1
```
On the official pytorch site, 1.2 and 1.4 are available, but not 1.3. How did you install?
https://pytorch.org/get-started/previous-versions/

Thank you for sharing the issue. Do you have the retrain models in newer pytorch versions?

**Comment by ewrfcas** [comment]
Unfortunately, we have no plan to retrain the model now.
Maybe we will update it in the future.
We can use pytorch1.3.1 in python3.6.13
![image](https://user-images.githubusercontent.com/12042259/168414046-575d96e8-6c10-4d2a-b350-12b998bcb369.png)
The cuda version is 10.0.

**Comment by naoki7090624** [comment]
Thank you for kind support.

I have successfully installed pytorch 1.3.1 on the cuda 10.2 (previously, I used 11.3), but it froze after executing ```lsm_hawp_inference.py```.
I think that problem is caused by cuda version and ampare gpu. According to the link, ampare gpus not support cuda 10.
https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
