### ISSUE TITLE
ZITS已经攀登了高峰，而进一步是需要惠民和普及

### ISSUE THREAD

**Issue by time888** [DQiaole/ZITS_inpainting#16]
ZITS在学术领域已经是很高端了，在代码具体调试和使用方面希望更能详尽，而进一步让更多的人了解并普及给广大民众。

**Comment by ewrfcas** [comment]
Thanks for your attention. We will improve the code and related issues.

**Comment by Sanster** [comment]
You can try ZITS using [Lama Cleaner](https://github.com/Sanster/lama-cleaner)
