### ISSUE TITLE
可否预上传一份pth样本，直接调试

### ISSUE THREAD

**Issue by time888** [DQiaole/ZITS_inpainting#18]
config_ZITS_places2.yml

transformer_ckpt_path: './ckpt/best_transformer_places2.pth'
gen_weights_path0: './ckpt/lama_places2/InpaintingModel_gen.pth'   # Not required at the time of eval
dis_weights_path0: './ckpt/lama_places2/InpaintingModel_dis.pth'   # Not required at the time of eval
structure_upsample_path: './ckpt/StructureUpsampling.pth'
------------------------------------

D:\pm\python\inpaint\ZITS_inpainting-main\ZITS_inpainting-main\src\models\FTR_model.py

    data = torch.load(config.structure_upsample_path, map_location='cpu')

发生异常: AttributeError
'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

During handling of the above exception, another exception occurred:

  File "D:\pm\python\inpaint\ZITS_inpainting-main\ZITS_inpainting-main\src\models\FTR_model.py", line 165, in __init__
    data = torch.load(config.structure_upsample_path, map_location='cpu')
  File "D:\pm\python\inpaint\ZITS_inpainting-main\ZITS_inpainting-main\src\models\FTR_model.py", line 427, in __init__
    super().__init__(*args, gpu=gpu, name='InpaintingModel', rank=rank, test=test, **kwargs)
  File "D:\pm\python\inpaint\ZITS_inpainting-main\ZITS_inpainting-main\src\FTR_trainer.py", line 256, in __init__
    self.inpaint_model = DefaultInpaintingTrainingModule(config, gpu=gpu, rank=rank, test=test, **kwargs).to(gpu)
  File "D:\pm\python\inpaint\ZITS_inpainting-main\ZITS_inpainting-main\single_image_test.py", line 323, in <module>
    model = ZITS(config, 0, 0, True)

----------------------

PS D:\pm\python\inpaint\ZITS_inpainting-main\ZITS_inpainting-main>  & 'D:\pm\python\python38\python.exe' 'c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy\launcher' '40191' '--' 'd:\pm\python\inpaint\ZITS_inpainting-main\ZITS_inpainting-main\single_image_test.py' '--path=D:\pm\python\lama\LaMa_models\lama-places\lama-fourier\models' '--config_file=D:\pm\python\inpaint\ZITS_inpainting-main\ZITS_inpainting-main\config_list\config_ZITS_places2.yml' '--GPU_ids=-1' '--img_path=D:\pm\python\inpaint\ZITS_inpainting-main\ZITS_inpainting-main\imgs\y\i1.png' '--mask_path=D:\pm\python\inpaint\ZITS_inpainting-main\ZITS_inpainting-main\imgs\mask\i1.png' '--save_path=D:\pm\python\inpaint\ZITS_inpainting-main\ZITS_inpainting-main\imgs'
Backend TkAgg is interactive backend. Turning interactive mode on.
BaseInpaintingTrainingModule init called
Loading InpaintingModel StructureUpsampling...

**Comment by ewrfcas** [comment]
You can download all pths in
https://drive.google.com/drive/folders/1Dg_6ZCAi0U3HzrYgXwr9nSaOLnPsf9n-?usp=sharing

**Comment by time888** [comment]
你好，我是在中国。现在在老家。Google域名的任何资源，在内地都访问不了。

是否可以提供新的镜向。更好普遍适应中国内地用户。

我下载调试过lama项目存储的那些文件。他好像是俄罗斯的镜向。

**Comment by time888** [comment]
> You can download all pths in https://drive.google.com/drive/folders/1Dg_6ZCAi0U3HzrYgXwr9nSaOLnPsf9n-?usp=sharing

你好，我是在中国。现在在老家。Google域名的任何资源，在内地都访问不了。

是否可以提供新的镜向。更好普遍适应中国内地用户。

我下载调试过lama项目存储的那些文件。他好像是俄罗斯的镜向。

**Comment by ewrfcas** [comment]
好的，近期我们会提交一个百度盘的版本。

**Comment by ewrfcas** [comment]
链接: https://pan.baidu.com/s/1LYIHabFNJSd0L3qDGYYYVw 提取码: qnm5
