### ISSUE TITLE
Questions/Issues about batch test evaluation.

### ISSUE THREAD

**Issue by ani0075saha** [DQiaole/ZITS_inpainting#27]
**Mask Image Correspondence**
If I am batch evaluating on a custom dataset, do I need to have the same number of masks as the number of evaluation images? How does the code decide correspondence between an image and mask? Is there any naming convention? I have generated the wireframes for all evaluation images. I have 1200 images. But the provided test masks are only 1000. I am wondering if the batch evaluation will work.

**Possible bug**
https://github.com/DQiaole/ZITS_inpainting/blob/main/src/FTR_trainer.py#L271
If test is True (batch eval), the self.val_dataset is never created.

Wouldn't https://github.com/DQiaole/ZITS_inpainting/blob/main/src/FTR_trainer.py#L443 throw an error?

**Comment by DQiaole** [comment]
**Mask Image Correspondence**
You don't need the same number of masks as the number of evaluation images. We just sort the masks according to their names and read the images according to a txt files (like the https://github.com/DQiaole/ZITS_inpainting/blob/main/places2_test_list.txt) to decide the correspondence between an image and mask. If masks less then images, we will reuse some masks:
https://github.com/DQiaole/ZITS_inpainting/blob/fac833f62d4ad1cee64cfe64872a08807d6d4d92/datasets/dataset_FTR.py#L382-L383

**Possible bug**
Thanks for point it out,  I have update the code and create the val_dataset when test.
