### ISSUE TITLE
Question about Wireframe extraction difference Single vs Batch mode

### ISSUE THREAD

**Issue by ani0075saha** [DQiaole/ZITS_inpainting#28]
It seems for **Single Image Test**, _the wireframe extraction is done for masked images_.
https://github.com/DQiaole/ZITS_inpainting/blob/main/single_image_test.py#L173 (Masking)
https://github.com/DQiaole/ZITS_inpainting/blob/main/single_image_test.py#L194 (Wireframe inference)
https://github.com/DQiaole/ZITS_inpainting/blob/main/single_image_test.py#L219 (obj_remove False, so use lines_masked and scores_masked). 
**Side Q.** When should obj_remove be used? _(The code also calculates wireframes for original image but it is not used if obj_remove is false)_.

But, for **Batch test**, _the wireframe extraction is done on original images_ (it is recommended to precompute the wireframes).
https://github.com/DQiaole/ZITS_inpainting#batch-test (precompute wireframes)
Then, the image, edge and line is masked before passing through transformer. 
https://github.com/DQiaole/ZITS_inpainting/blob/main/src/utils.py#L273

**Q.** I am not an expert in wireframe extraction. But, wouldn't passing a masked image for wireframe extraction vs passing the full image and then masking give different results? Or is it the same and it doesn't matter? Ideally, for inpainting, we wouldn't have access to the original unmasked images and cannot extract wireframes on them. Why this difference in implementation?

**Comment by ewrfcas** [comment]
Thanks for this point. We follow MST(https://github.com/ewrfcas/MST_inpainting) with the masking augmented line detector (LSM-HAWP). Thus LSM-HAWP can achieve good results even in masked images. 
Here is an instance.
<img width="895" alt="image" src="https://user-images.githubusercontent.com/12042259/172598636-1a4eb318-6e08-4339-9e79-23ba64b3f869.png">
Random masking is also a useful augmentation to improve the normal wireframe detection as discussed in MST.
<img width="525" alt="image" src="https://user-images.githubusercontent.com/12042259/172598793-53face00-ac43-402e-8418-38a8ac068c11.png">
For a single image test, we provide more choices (using or not using original lines with 'obj_remove') during the inference.
For batch testing, we think there is a little gap between 'lines from masked images' and 'masked lines from images', but the gap can be neglected in our practices.
