### ISSUE TITLE
Access to the pre-trained model

### ISSUE THREAD

**Issue by roimulia2** [DQiaole/ZITS_inpainting#3]
Loved the paper! The results compare to LaMa are amazing. 
Can I have access to the lightest pre-trained model? (Benchmarking on mobile devices) 

Best regards,
Roi

**Comment by ewrfcas** [comment]
Thanks for the attention. Models and inference codes are released now.

**Comment by roimulia2** [comment]
Awesome, thanks! Do you think this model can be used on Mobile as well? In terms of performace and ram usage?

**Comment by ewrfcas** [comment]
I think this model is still difficult to be used on mobiles. For lower ram usage, both image resolution and model parameters should be reduced. We will further explore simplifying our model.

**Comment by roimulia2** [comment]
I just sent you an email 👍🏻
