### ISSUE TITLE
Provide discriminator weights

### ISSUE THREAD

**Issue by ani0075saha** [DQiaole/ZITS_inpainting#30]
The config file contains this line:
dis_weights_path0: './ckpt/lama_places2/InpaintingModel_dis.pth'

Can you please provide these weights? Or point me to where I can get them?

**Comment by DQiaole** [comment]
Hi,
This path indicates the pre-trained LaMa models. If you want a pure LaMa model, you can download them from the official repo (there maybe some naming difference between mine and the official one) or train the LaMa according to our command:
```
python FTR_train.py --nodes 1 --gpus 1 --GPU_ids '0' --path ./ckpt/lama_places2 --config_file ./config_list/config_LAMA.yml --lama
```
