### ISSUE TITLE
inference/latency time benchmark against LaMa 

### ISSUE THREAD

**Issue by roimulia2** [DQiaole/ZITS_inpainting#31]
Hey, loved your paper! 

Did you by chance compared your model to LaMa in terms of speed/memory usage/CPU.GPU usage etc'? Super interesting.

Thanks!

**Comment by DQiaole** [comment]
Hi,
The main additional cost of our model compared to LAMA stems from TSR. And we have provided information such as the memory footprint and inference speed of the TSR in Table 3 of the supplementary material.

**Comment by roimulia2** [comment]
Thank you for the fast response.
I'm a newbie when it comes to ML, I searched within the paper but couldn't find it (maybe I don't know what is the shortcut to inference speed/ memory).
If it's okay, Can you tell me exactly what should I be looking for? Sorry for the trouble!

**Comment by DQiaole** [comment]
Hi,
you can find it from:
https://openaccess.thecvf.com/content/CVPR2022/supplemental/Dong_Incremental_Transformer_Structure_CVPR_2022_supplemental.pdf
pages 6, table 3.

**Comment by roimulia2** [comment]
Thank you @DQiaole! You really did amazing work.
When looking at the GPU seems like it ranges from 10GB-14GB.
I was wondering, is it possible to run the model on mobile devices? Even if it'll be slower.

**Comment by DQiaole** [comment]
Sorry, I don't know much about mobile devices.

**Comment by roimulia2** [comment]
Okay, thanks! :)
