### ISSUE TITLE
Bad results

### ISSUE THREAD

**Issue by mhashas** [DQiaole/ZITS_inpainting#32]
I am getting some very poor results. I am using the single_image script and resizing images to 512,512

<img width="511" alt="image" src="https://user-images.githubusercontent.com/13119609/176773336-f2c41136-24df-4f8c-9266-4adaef84f5ff.png">
<img width="510" alt="image" src="https://user-images.githubusercontent.com/13119609/176773404-f294c745-a716-4864-a4d6-65809a4e29a6.png">
<img width="625" alt="image" src="https://user-images.githubusercontent.com/13119609/176773433-3f3a51e6-f9e1-477d-8ea0-d5f3e4922f96.png">

Can some of the images + masks from the showed resuts can be shared? This way I could verify if I did something weird

**Comment by DQiaole** [comment]
Hi~
I have testes your image, and the result is as follow:
![img](https://user-images.githubusercontent.com/49903017/176838806-f0f98ec4-7822-4313-b575-bb92695b94fb.png)

Besides, I also upload our test images to directory "test_imgs".

**Comment by mhashas** [comment]
Thanks a lot, I will check whats happening. Just to make completely sure, the mask you send to the network is the 3rd image, not the second, correct?

**Comment by DQiaole** [comment]
Yes, you are right. We send the 3rd image as our mask.

**Comment by mhashas** [comment]
Hi,

For the test images it does indeed work well. However, for single_image_test, the image needs to be 2^k. How did you do the resizing of the image for my example?

**Comment by mhashas** [comment]
Removing center cropping fixed it for me
