### ISSUE TITLE
lsm_hawp_inference.py_result_bad

### ISSUE THREAD

**Issue by bobo0303** [DQiaole/ZITS_inpainting#33]
I try to use the lsm_hawp_inference.py to generate the .pkl of my dataset (place365).
I used the best_lsm_hawp.pth which you provided.
But the result is really bad.
I tried reduce threshold=0.8 > 0.5 but it still has bad result.

Do you have the best_palce365_lsm_hawp.pth?
Or how do we train our own hawp.

The iamge is the sample from training.(14001.jpg)
![image](https://user-images.githubusercontent.com/56902242/177194668-dbd7052d-4e10-4561-88c3-79912b6a6eae.png)

**Comment by DQiaole** [comment]
Hi~
You can try the test images we provide under directory 'test_imgs' and if the results are consistent with ours, there is no problem.

**Comment by bobo0303** [comment]
Can you tell me how do you generate the GT to train hawp?

**Comment by bobo0303** [comment]
I tried the 'test_imgs' the results are consistent with yours. 
But when I choose my own train dataset the line image will be bad so the training model will not be good at line image.

Do you have some suggest for choosing image?

Image is the line image result by my own dataset.
![image](https://user-images.githubusercontent.com/56902242/177301041-0e96b0f8-9987-4dce-b31c-799deb9546fb.png)

**Comment by DQiaole** [comment]
I think it's due to the lack of meaningful lines (wireframes) in your images themselves.
As for choosing images, I think our **indoor** images are a good choice.

**Comment by Ellohiye** [comment]
![image](https://user-images.githubusercontent.com/57579741/178392279-405d5e97-cf82-4a3e-a017-3dae1e7b88c5.png)
I also encountered this problem, training with the Indoor dataset, which is the 96100th picture, and the line segment does not work well.

**Comment by DQiaole** [comment]
Please try this first.
https://github.com/DQiaole/ZITS_inpainting/issues/33#issuecomment-1174503971

**Comment by Ellohiye** [comment]
> 
Hi,have you trained on the Indoor dataset and how is the result?

> Please try this first. [#33 (comment)](https://github.com/DQiaole/ZITS_inpainting/issues/33#issuecomment-1174503971)

ok!!! I will try it later. The lab having a power cut.

**Comment by Ellohiye** [comment]
> I tried the 'test_imgs' the results are consistent with yours. But when I choose my own train dataset the line image will be bad so the training model will not be good at line image.
> 
> Do you have some suggest for choosing image?
> 
> Image is the line image result by my own dataset. ![image](https://user-images.githubusercontent.com/56902242/177301041-0e96b0f8-9987-4dce-b31c-799deb9546fb.png)

Hi!!! Have you trained in the Indoor data set? How's the result?

**Comment by bobo0303** [comment]
@yunbingbing bad too.
I read HAWP and MST paper. The new LSM-MHAWP should not be bad like that.
Maybe the dataset of the pretraind model is too deffrient with my train dataset. 
So I give up the line image.

**Comment by Ellohiye** [comment]
This is the result of the test image,![image](https://user-images.githubusercontent.com/57579741/178685224-513f40fe-57b6-4235-bdea-720578698e6d.png)

**Comment by DQiaole** [comment]
Your results are clearly problematic. I think there may be some problems with your environment, as HAWP is sensitive to the environment. You can refer to the environment configuration we provide.

**Comment by Ellohiye** [comment]
> Your results are clearly problematic. I think there may be some problems with your environment, as HAWP is sensitive to the environment. You can refer to the environment configuration we provide.

![image](https://user-images.githubusercontent.com/57579741/179155514-4b0d1179-6664-42f9-bac6-d86845e85ab4.png)
Thank you very much! I reconfigured the environment and found that the line segment generation worked well. I will train on the indoor dataset later. I have a small question to ask, how do I convert a file in pkl format to jpg?

**Comment by DQiaole** [comment]
https://github.com/DQiaole/ZITS_inpainting/blob/ef3b0c36e55d8e9650487424d8302a12dabd4525/datasets/dataset_TSR.py#L119-L133

**Comment by Ellohiye** [comment]
> https://github.com/DQiaole/ZITS_inpainting/blob/ef3b0c36e55d8e9650487424d8302a12dabd4525/datasets/dataset_TSR.py#L119-L133

Thank you!!!!
