### ISSUE TITLE
TSR_inference.py quesetion

### ISSUE THREAD

**Issue by bobo0303** [DQiaole/ZITS_inpainting#34]
The code line: 47 48
 test_dataset = ContinuousEdgeLineDatasetMask(opts.image_url, test_mask_path=opts.mask_url, is_train=False,
                                                 image_size=opts.image_size)

Dose the code loss 'line_path'?
I think it should be like this.

parser.add_argument('--test_line_path', type=str, default=' ', help='Indicate where is the wireframes of test set')

 test_dataset = ContinuousEdgeLineDatasetMask(opts.image_url, test_mask_path=opts.mask_url, is_train=False,
                                                 image_size=opts.image_size,line_path=opts.test_line_path)

If I am wrong. Please tell me.

**Comment by DQiaole** [comment]
Thanks for your reminder! I have updated the code.
