### ISSUE TITLE
Mask Question

### ISSUE THREAD

**Issue by wangweiran0922** [DQiaole/ZITS_inpainting#37]
Hello, I want to ask why there are two masks in data_TSR.py？ Will using only one mask affect the experimental results？
Looking forward to your reply.

**Comment by DQiaole** [comment]
Hellos, we use two masks to tackle the real-world object removal task, following the mask setting from MST, which includes irregular masking brushes and COCO segmentation masks with masking rates from 10% to 50%.
I think use one mask will indeed affect the experimental results.
