### ISSUE TITLE
Data problem

### ISSUE THREAD

**Issue by Changxiaokui** [DQiaole/ZITS_inpainting#39]
Hi, I tried FTR_inference.py.But I don't know What are the training and verification images set in config.yml. Is the edge and line generated by TSR? I hope to receive your explanation.
  Looking forward to your reply,thanks.

**Comment by DQiaole** [comment]
Hi, the training and verification images set in config.yml are the training and validation set of Places2; and there is no need to modify the 'train_line_path'/'eval_line_path' in config, it will automatically use the edge and line generated by TSR using the correspondence weight 'transformer_ckpt_path'.
