### ISSUE TITLE
Single image test

### ISSUE THREAD

**Issue by CodeMadUser** [DQiaole/ZITS_inpainting#40]
你好，作者，你做的工作非常棒，只是我在进行源码测试时有一些疑问：在下面的配置设置中
python single_image_test.py --path <ckpt_path> --config_file <config_path> \
 --GPU_ids '0' --img_path ./image.png --mask_path ./mask.png --save_path ./
权重path使用哪个呢？config_file使用哪个文件呢？我自己设置的设置如下：
python single_image_test.py --path ./ckpt/zits_places2_hr --config_file ./config_list/config_ZITS_HR_places2.yml --GPU_ids '0' --img_path ./test_i/img1.png --mask_path ./test_i/mask1.png --save_path ./test_i/
但是出现了下面的错误：
Traceback (most recent call last):
  File "single_image_test.py", line 322, in <module>
    model = ZITS(config, 0, 0, True)
  File "D:\pythonProject\7_4\inpaint\ZITS_inpainting-main\src\FTR_trainer.py", line 296, in __init__
    min_sigma=min_sigma, max_sigma=max_sigma)
  File "D:\pythonProject\7_4\inpaint\ZITS_inpainting-main\datasets\dataset_FTR.py", line 178, in __init__
    f = open(flist, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/wmlce/places365_standard/places2_all/test_sub_list.txt'

单图测试也需要跟数据集一样的设置吗？希望能将测试步骤更加详细一些。希望能回复，非常感谢。希望能将测试步骤更加详细一些。

**Comment by DQiaole** [comment]
你好，不需要验证集的设置，我额外添加了一个参数，现在应该可以运行了。
权重path和config_file可以参考我们512的设置就行。

**Comment by CodeMadUser** [comment]
> 你好，不需要验证集的设置，我额外添加了一个参数，现在应该可以运行了。 权重path和config_file可以参考我们512的设置就行。

对新的代码进行了测试，无法正常保存结果，如下：
PS D:\pythonProject\7_4\ZITS_inpainting-main> python single_image_test.py --path ./ckpt/zits_places2_hr --config_file ./config_list/config_ZITS_HR_places2.yml --GPU_ids '0' --img_path ./test_i/img1.png --mask_path ./test_i/mask1.png
 --save_path ./test_i/
BaseInpaintingTrainingModule init called
Loading InpaintingModel StructureUpsampling...
Loading trained transformer...
Loading InpaintingModel generator...
Warnning: There is no previous optimizer found. An initialized optimizer will be used.
Warnning: There is no previous optimizer found. An initialized optimizer will be used.
load HAWP
single_image_test.py:127: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted 
the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  edge_256 = canny(gray_256, sigma=sigma256, mask=None).astype(np.float)
D:\pythonProject\7_4\ZITS_inpainting-main\src\models\ffc.py:46: UserWarning: The function torch.rfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.
fft and calling torch.fft.fft or torch.fft.rfft. (Triggered internally at  ..\aten\src\ATen\native\SpectralOps.cpp:590.)
  ffted = torch.rfft(x, signal_ndim=2, normalized=True)
D:\pythonProject\7_4\ZITS_inpainting-main\src\models\ffc.py:58: UserWarning: The function torch.irfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch
.fft and calling torch.fft.ifft or torch.fft.irfft. (Triggered internally at  ..\aten\src\ATen\native\SpectralOps.cpp:602.)
  signal_sizes=r_size[2:], normalized=True)

saving sample img1.png

没有结果保存在test_i中，不知道怎么回事

**Comment by DQiaole** [comment]
可能是多了一个“/”
```
python single_image_test.py --path ./ckpt/zits_places2_hr --config_file ./config_list/config_ZITS_HR_places2.yml --GPU_ids '0' --img_path ./test_i/img1.png --mask_path ./test_i/mask1.png
--save_path ./test_i
```
或者是./test_i/img1.png已经被覆盖了。

**Comment by CodeMadUser** [comment]
> 可能是多了一个“/”
> 
> ```
> python single_image_test.py --path ./ckpt/zits_places2_hr --config_file ./config_list/config_ZITS_HR_places2.yml --GPU_ids '0' --img_path ./test_i/img1.png --mask_path ./test_i/mask1.png
> --save_path ./test_i
> ```
> 
> 或者是./test_i/img1.png已经被覆盖了。

非常感谢，问题解决了。覆盖了。
