### ISSUE TITLE
Any way to retain RGB values greater 1.0?

### ISSUE THREAD

**Issue by OverwriteDev** [DQiaole/ZITS_inpainting#43]
First off, fantastic work on this model!
I've been having a great time digging through the code and figuring out how everything works. 
I've added the ability to write out EXR files along with color management using opencolorio.

One thing that I can't seem to figure out is how to maintain image float values above 1.0 and below 0.
They seem to be getting clamped somewhere between loading the image and writing the predicted image to an image file.
I've gone through everything to make sure that image values aren't being clipped but I think I may have missed something.

Any help with this would be very much appreicated.

**Comment by DQiaole** [comment]
Hi~
we use tanh activation function at the output end, so the predicted image will between 0 and 1 after normalization.
https://github.com/DQiaole/ZITS_inpainting/blob/6fd5fc0518eac201032ea1d90fd71310b9050a77/src/models/LaMa.py#L195-L196

**Comment by OverwriteDev** [comment]
That was very helpful, thank you!
