### ISSUE TITLE
inpainting_metrics.py中ValueError: axes don't match array错误

### ISSUE THREAD

**Issue by Ellohiye** [DQiaole/ZITS_inpainting#44]
作者你好，在文件的这行代码出现上述问题
![image](https://user-images.githubusercontent.com/57579741/192984374-6a3cd7fb-53a5-4e42-a5a6-8f6075e4986f.png)
如果此时传入的是indoor数据集的原图像，不是256*256大小的，根据博客：https://stackoverflow.com/questions/37747021/create-numpy-array-of-images 给出的方法，对图像进行处理后可以正常运行，但是不知道这样是否会对结果产生影响。
![image](https://user-images.githubusercontent.com/57579741/192984880-93892929-ad08-4ae6-95cc-4b941d2d7e22.png)
我想知道你们有遇到过这个问题吗？能否给我一点建议呢？期待您的回复，谢谢

**Comment by DQiaole** [comment]
你好，
我们会事先将所有图像下采样到同一个分辨率（256*256或者512*512)，再计算相应的fid；你也可以在173行处cv2.imread后加上cv2.resize将读取的图片resize后，再append到list中。

**Comment by Ellohiye** [comment]
是的 我是按照“你也可以在173行处cv2.imread后加上cv2.resize将读取的图片resize后，再append到list中”这个方式解决的，请问“我们会事先将所有图像下采样到同一个分辨率（256256或者512512)，再计算相应的fid”这个对应的代码在哪里呀？我看了源代码计算fid部分时，看到只是通过图片路径来读取出图片，并没有看到下采样部分

**Comment by DQiaole** [comment]
这部分代码属于数据预处理，比较简单，我并没有上传。我的图片路径下是所有已经resize过的图片，你可以把resize后的图片存到一个文件夹中即可。

**Comment by Ellohiye** [comment]
好的，我明白了！非常感谢作者的耐心解答
