### ISSUE TITLE
Config files, prediction steps and seeds.

### ISSUE THREAD

**Issue by OverwriteDev** [DQiaole/ZITS_inpainting#45]
Hi there!

I've been looking for parameters to manipulate both in the config files and code base that will allow me to control inpaint generation variables, such as how many steps go into predicting an image and how to change the seed in order to get a variation of the generated inpaint image. I've tried modifying the config files and setting the seed via the function provided but it doesn't seem to have any effect on the result.

Any assistance with getting me started in the right direction would be appreciated 🙏

**Comment by DQiaole** [comment]
Hi~
our method is a determinstic algorithm, the seed is corresponding to the training process.
As for the TSR inference steps, you can change the iterations below;
https://github.com/DQiaole/ZITS_inpainting/blob/6fd5fc0518eac201032ea1d90fd71310b9050a77/single_image_test.py#L243-L246

**Comment by OverwriteDev** [comment]
Thank you for sharing that!
I'm curious, what role do the add_v and mult_v play in the process and what do they contribute to the SampleEdgeLineLogits function?
