### ISSUE TITLE
why the cited fid values are different  from that in the original paper? 

### ISSUE THREAD

**Issue by micklexqg** [DQiaole/ZITS_inpainting#47]
the cited fid value which is from MST is this:
![image](https://user-images.githubusercontent.com/13776012/194264830-80720aaf-9460-4ae3-ac8f-71c7c836f05e.png)

while the original fid value from MST is this:
![image](https://user-images.githubusercontent.com/13776012/194266943-1d8cd205-b3d2-4454-915b-1c0e317e6bd1.png)

Why they are different?

Another question, is the code for computing fid score right? why my results got by the given code are very high, can you provide several results (the results in the paper do not include ground truth)

**Comment by DQiaole** [comment]
Because MST randomly select 10 Places2 classes with both natural and urban scenes as comprehensive scenes (P2C), which is a subset of places2 dataset.
Besides, our code of fid is right as below:
https://github.com/DQiaole/ZITS_inpainting/blob/main/src/inpainting_metrics.py
