### ISSUE TITLE
MPE module

### ISSUE THREAD

**Issue by Ellohiye** [DQiaole/ZITS_inpainting#51]
![image](https://user-images.githubusercontent.com/57579741/200775647-997e4ef4-ade0-4969-b053-446399bd5129.png)

Hello author, how is the ablation experiment of the MPE module designed in this table in the paper?
(1) Is it the result of fine-tuning with ReZero?
(2) Or directly add the MPE module to the Lama model for training?
Looking forward to your reply! Thanks!

**Comment by DQiaole** [comment]
Hi!
This result is tested **without** ReZero, we directly add the MPE module to the Lama model for training.

**Comment by Ellohiye** [comment]
> Hi! This result is tested **without** ReZero, we directly add the MPE module to the Lama model for training.

OK! thank you for your reply!
