### ISSUE TITLE
baseline

### ISSUE THREAD

**Issue by Ellohiye** [DQiaole/ZITS_inpainting#55]
Hello author, when you compared other baseline models, did you use the mask generated in this paper and the corresponding data set to retrain the baseline model? Like the lama model，did you use which type of mask?Looking forward to your reply！

**Comment by DQiaole** [comment]
Sure, we use the same mask proposed in our paper for all models. Besides, we retrain all models in our Indoor dataset. As for Places2, we only retrain the MST and LaMa.

**Comment by Ellohiye** [comment]
好的，感谢作者的回复呀。那对于places2的其他基线模型，还是用的基线模型原论文中掩码吗?

---Original---
From: "Qiaole ***@***.***&gt;
Date: Mon, Dec 12, 2022 23:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [DQiaole/ZITS_inpainting] baseline (Issue #55)




 
Sure, we use the same mask proposed in our paper for all models. Besides, we retrain all models in our Indoor dataset. As for Places2, we only retrain the MST and LaMa.

**Comment by Ellohiye** [comment]
> Sure, we use the same mask proposed in our paper for all models. Besides, we retrain all models in our Indoor dataset. As for Places2, we only retrain the MST and LaMa.

Thank you very much for your detailed reply! I want to do a comparative experiment recently, can I ask you some questions? For each model (other baseline models), do I have to guarantee that the mask is the same for all models when training? For example, I trained my model according to the design of the 512*512 image mask in lama. When I compare AOTGAN, can I directly use the official pre-trained model to evaluate the results, or must I retrain AOTGAN on the same mask?
