### ISSUE TITLE
the path in config 

### ISSUE THREAD

**Issue by ErisGe** [DQiaole/ZITS_inpainting#56]
modify the image path  
**# origin images?**
TRAIN_FLIST: ./data_list/sp_large_train_list.txt   
VAL_FLIST: ./data_list/sp_large_val_list.txt
TEST_FLIST: ./data_list/sp_large_val_list.txt

set the GT images folder for metrics computation  
**# origin Val image?**
GT_Val_FOLDER: './datasets/inpaint_data/val_images/'

modify the mask path  
**# the mask of random generation?**
TRAIN_MASK_FLIST: [ './data_list/mask_large_train_list.txt',
                    './data_list/mask_large_train_list.txt' ]

**the real mask of object when object remove?**
TEST_MASK_FLIST: ./datasets/inpaint_data/val_SH_binary_masks/

Could you tell me that the mean of these path in my mind is right?

**Comment by DQiaole** [comment]
Hi, most are right. But 'TEST_MASK_FLIST' indicates the folder of masks used for test or val images, it does not mean for object removal.
