### ISSUE TITLE
continue train

### ISSUE THREAD

**Issue by Littlechickencub** [DQiaole/ZITS_inpainting#58]
请问我想使用自己的数据集进行继续训练的话，是只需要训练FTR_train还是TSR_train和SSU都要训练？

**Comment by DQiaole** [comment]
SSU不需要训练；FTR_train和TSR_train需要重新训练。

**Comment by Littlechickencub** [comment]
您好，我看见places2_continous_edgeline文件夹里没有训练好的模型，我自己做了数据集，想对TSR_train继续训练，请问您那边有没有训练好的模型和继续训练的代码，感谢


553295098
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DQiaole/ZITS_inpainting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月25日(星期六) 晚上11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DQiaole/ZITS_inpainting] continue train (Issue #58)





 
Closed #58 as completed.

**Comment by DQiaole** [comment]
Hi, Please Download the pretrained models on Places2 [here](https://drive.google.com/drive/folders/1Dg_6ZCAi0U3HzrYgXwr9nSaOLnPsf9n-?usp=sharing).

Link for [BaiduDrive](https://pan.baidu.com/s/1LYIHabFNJSd0L3qDGYYYVw), password:qnm5
