### ISSUE TITLE
The path problems

### ISSUE THREAD

**Issue by BigConsin** [DQiaole/ZITS_inpainting#59]
Hi,there! Just read your cvpr papers,andi am confused about the 'valid_mask_path' in the TSR_train.py(line 86),i just don't know what that supposed to be. 

- Here's my understandings about the train path,please correct me if i was wrong.
- 1.data_path and validation_path means the dataset's(indoor&places2) train and val set.
- 2.train_line_path and val_line_path means the train wireframes and val wireframes extracted from datasets with lsm_hawp_inference.py.
- 3.The valid_mask_path i didn't see its' mask_val_list in your codes,i guess it's the test masks?

And i would like to konw how many gpus you guys use and how long would this model run.

Thanks for your great work and looking forward to your reply!

**Comment by DQiaole** [comment]
Hi!
your understandings are right.  'valid_mask_path'  is the unzipped test_masks.zip provide in
https://github.com/DQiaole/ZITS_inpainting/tree/main/data_list

Our TSR can be trained in batch size 30 with 3 NVIDIA(R) Tesla(R) V100 16GB GPUs. The training times depends on the datasets. More Training Details can be found in our supplementary.

**Comment by BigConsin** [comment]
Oh i see,thanks a lot.
