### ISSUE TITLE
About Transformer Block

### ISSUE THREAD

**Issue by naoki7090624** [DQiaole/ZITS_inpainting#6]
Thank you for sharing your great works!!

I have two questions.

1. Could you explain your transformer block in Fig.2 of your paper? 
According to your code, the transformer block consists of the following layers.
AxialAttention -> my_Block_2(CausalSelfAttention + MLP)
I think the first feedforward refers to CausalSelfAttention and Vanilla Attention refers to MLP, but what is the last feedforward?

2. What is the differences between your transformer block and ICT transformer block?

Thank you in advance.

**Comment by DQiaole** [comment]
Hi!
For question 1:
in our code,  the transformer block consists of BlockAxial (attn_row + attn_col + FFN) and my_Block_2 (attn + MLP); where the first feedforward refers to FFN, Vanilla Attention refers to attn and the last feedforward refers to MLP.

For question 2:
there is no axial attention block and relative position encoding in ICT transformer block, besides, we employ CNN stem as the feature extractor, and the inductive bias bring by convolution is also useful.

**Comment by naoki7090624** [comment]
Thank you so much for clear and informative answers
