### ISSUE TITLE
FTR_train

### ISSUE THREAD

**Issue by LYL-hub-source** [DQiaole/ZITS_inpainting#60]
Hello author, I have installed APEX, but only one GPU. When I train FTR, I change the code to “python FTR_train.py --nodes 1 --gpus 1 --GPU_ids '0' --path ./ckpt/mural --config_file ./config_list/config_ZITS_places2.yml” Then the following error occurred：
![2023-03-19 17-29-51 的屏幕截图](https://user-images.githubusercontent.com/82621485/226167664-4abc983e-94a0-4854-8350-c3a2456a9b74.png)
![2023-03-19 17-18-21 的屏幕截图](https://user-images.githubusercontent.com/82621485/226167674-a29e3cf3-890e-4f40-9631-11f9235fe256.png)

**Comment by DQiaole** [comment]
Hi, I think you may load the best performed model of LAMA (suffix with '_best_gen.pth'), where we don't save the optimizer's parameter. In our experiment, we initialize the FTR with latest saved model (suffix with '_gen.pth').

**Comment by LYL-hub-source** [comment]
This problem has been solved, thank you very much
