### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by LYL-hub-source** [DQiaole/ZITS_inpainting#61]
Hello author, I have completed FTR.train. When doing BATCH TEST, I used my own TEST and MASK data sets of 100 each.Input code: python FTR_inference.py --path ./ckpt/zits_mural --config_file ./config_list/config_ZITS_places2.yml --GPU_ids '0'
![2023-03-21 12-04-28 的屏幕截图](https://user-images.githubusercontent.com/82621485/226514879-3cb66c89-eea6-4770-85bd-5ffc0cf8bb0f.png)

yml:
![2023-03-21 12-02-23 的屏幕截图](https://user-images.githubusercontent.com/82621485/226514681-162bf10e-2b68-46f1-a8a6-2a7cf692cfca.png)

After that I changed TEST_MASK_FLIST to /home/liu/WH/ZITS_inpainting-main/mural_datasets/mask_10/Test_mask_10
![2023-03-21 21-27-41 的屏幕截图 - 1](https://user-images.githubusercontent.com/82621485/226621170-b33a5046-241c-4d0a-8fc6-7f6cf25dd6fe.png)

**Comment by DQiaole** [comment]
Hi, TEST_MASK_FLIST should be a directory of masks. And we define 'self.log_file' during training, you can modify the codes if you want to save the test results to a file:
https://github.com/DQiaole/ZITS_inpainting/blob/208fe52e62c3c126aec0823cadc11081f32d90cb/src/FTR_trainer.py#L287
