### ISSUE TITLE
why is there shadow in merged output?

### ISSUE THREAD

**Issue by micklexqg** [DQiaole/ZITS_inpainting#63]
![image](https://user-images.githubusercontent.com/13776012/232319304-9eb547ca-c218-4002-8947-67050bf462ab.png)

there is shadow in the merged output, but not in the predicted image which is not merged.  there are some small pixel differences between  the merged output and the predicted image.
so why is there shadow in merged output?

**Comment by DQiaole** [comment]
please refer to https://github.com/DQiaole/ZITS_inpainting/issues/62

**Comment by Hzyy99** [comment]
> ![image](https://user-images.githubusercontent.com/13776012/232319304-9eb547ca-c218-4002-8947-67050bf462ab.png)
> 
> there is shadow in the merged output, but not in the predicted image which is not merged. there are some small pixel differences between the merged output and the predicted image. so why is there shadow in merged output?

Hello, I also met the same problem, may I ask whether you have solved this problem
