### ISSUE TITLE
Socket error Event: 32 Error: 10053. 

### ISSUE THREAD

**Issue by Littlechickencub** [DQiaole/ZITS_inpainting#68]
Connection closing...Socket close. Connection closed by foreign host.  Disconnected from remote host(Cy_lap) at 12:03:51.我用的Xshell 7 连的实验室的服务器，使用places2数据集训练LaMa，但是经常会报这个错误，就是训着训着突然就报这个错误，今天是在第一轮保存模型到5380的时候又报了这个错误，上次是有这个提醒torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGKILL，我就改小了num_workers为8，batch_size为8。我的设备型号是 GTX1070 4个，每个GPU显存都是8GB,可用内存104G，磁盘可用内存483G，CPU个数2个，核心数12，processor:48，型号Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz，请问怎么改？感谢

**Comment by DQiaole** [comment]
你好，我们没有遇到过这个问题。
