### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by clcllllll** [DQiaole/ZITS_inpainting#69]
Hello, when I train TSR_train.py with my own dataset, I encounter this error. Could you please tell me what might be causing it?
![image](https://github.com/DQiaole/ZITS_inpainting/assets/59495443/bf310f59-8b3b-44f7-9b89-4479268765ac)

**Comment by DQiaole** [comment]
Hello, I think there maybe less masks then images, you may need read mask by 
self.mask_list[index%len(self.mask_list)]

**Comment by clcllllll** [comment]
Hello, it seems that your suggestion is correct. I reduced some of the images and the program is now running smoothly. Thank you!

**Comment by clcllllll** [comment]
Also, I would like to ask, where does the file GT_Val_FOLDER: '/home/wmlce/places365_standard/val_256img_for_eval come from?

**Comment by DQiaole** [comment]
We resize all the validation/test images from Places365 into resolution of 256x256 for fast evaluation. And 'val_256img_for_eval' is the directory where we save these resized images.

**Comment by clcllllll** [comment]
You are so patient and gentle, thank you very much!
