### ISSUE TITLE
No usable temporary directory found in

### ISSUE THREAD

**Issue by clcllllll** [DQiaole/ZITS_inpainting#70]
![image](https://github.com/DQiaole/ZITS_inpainting/assets/59495443/ea59e74d-5682-4036-88c4-6c9581543d84)
I'm sorry to bother you, but I'm getting this error after training for a while. What could be the reason for it?

**Comment by DQiaole** [comment]
Hi, I think you system has no disk space left.

**Comment by clcllllll** [comment]
The issue has been resolved, thank you。
