### ISSUE TITLE
关于配置文件的问题

### ISSUE THREAD

**Issue by Mayingj** [DQiaole/ZITS_inpainting#73]
您好！感谢您的工作！我有些问题想请教您！我在运行您的代码时（test时），在配置文件中遇到了-eval_line_path，请问该地址所包含的文件，我应该如何获得？

**Comment by DQiaole** [comment]
你好，这是我们用lsm_hawp抽取数据集的wireframes后保存下来的wireframes文件夹地址：
```
conda activate train_env
python lsm_hawp_inference.py --ckpt_path <best_lsm_hawp.pth> --input_path <input image path> --output_path <output image path> --gpu_ids '0'
```
如果是单张图像推断的话，可以使用如下代码，其会自动抽取wireframes：
```
conda activate train_env
python single_image_test.py --path <ckpt_path> --config_file <config_path> \
 --GPU_ids '0' --img_path ./image.png --mask_path ./mask.png --save_path ./
```
如果是训练的话，请提前抽取wireframes加快训练速度。

**Comment by Mayingj** [comment]
非常感谢您的回复，我已经解决的了问题，很感谢。
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Oct 10, 2023 10:18 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [DQiaole/ZITS_inpainting] 关于配置文件的问题 (Issue #73)

&nbsp;



 
你好，这是我们用lsm_hawp抽取数据集的wireframes后保存下来的wireframes文件夹地址。如果是单张图像推断的话，可以使用如下代码，其会自动抽取wireframes。
 conda activate train_env python single_image_test.py --path <ckpt_path&gt; --config_file <config_path&gt; \  --GPU_ids '0' --img_path ./image.png --mask_path ./mask.png --save_path ./  
如果是训练的话，请提前抽取wireframes加快训练速度。
