### ISSUE TITLE
Regarding zeroRA in model retraining

### ISSUE THREAD

**Issue by LanTianBy** [DQiaole/ZITS_inpainting#80]
Thank you for this excellent work. If I need to train a model (including a generator) from scratch, will zeroRA still function in the same way as in the paper?

**Comment by LanTianBy** [comment]
What I also want to know is, can I turn off zeroRA fine-tuning and train the whole model from scratch? (All modules are trained at the same time). Thank you.

**Comment by DQiaole** [comment]
Sure, when you train the whole model (including a generator, structure encdoer) from the scratch, you can turn off the ZeroRA. As we designed ZeroRA for the purpose of introducing structure guidance infomation into the pretrained generator. This idea has also be applied in following works, such as ControlNet.

**Comment by LanTianBy** [comment]
> Sure, when you train the whole model (including a generator, structure encdoer) from the scratch, you can turn off the ZeroRA. As we designed ZeroRA for the purpose of introducing structure guidance infomation into the pretrained generator. This idea has also be applied in following works, such as ControlNet.

Thank you for your quick and effective answer. Thanks again!
