### ISSUE TITLE
Should alpha in SFE be removed?

### ISSUE THREAD

**Issue by LanTianBy** [DQiaole/ZITS_inpainting#81]
Hi, should I set the alpha in the SFE to 1 or just remove them when I retrain the whole model? Because I noticed that they were initialized to 0.
![1721096629997](https://github.com/user-attachments/assets/592fab75-04cb-42ad-82f3-946d111bd273)

**Comment by DQiaole** [comment]
sure, you can remove them when train the whole model (including the generator) from the scratch.

**Comment by LanTianBy** [comment]
> sure, you can remove them when train the whole model (including the generator) from the scratch.

thanks！
