### ISSUE TITLE
I apologize for the disturbance again, regarding the query about L1LOSS in the paper

### ISSUE THREAD

**Issue by LanTianBy** [DQiaole/ZITS_inpainting#82]
I noticed that the paper calculates the L1 loss between the predicted image's unmasked region and the actual image's unmasked region. What is the significance of this? My understanding is that should we calculate the L1 loss between the repaired (masked) regions?
![1721307097198](https://github.com/user-attachments/assets/ef5234b2-977c-47aa-8e74-046e17a48dc6)

**Comment by DQiaole** [comment]
Firstly, calculates the L1 loss for unmasked region can promote the generated images preserving the unmasked content. Secondly, we may not expect the inpainted image to reproduce the content within the masked regions, for example, when we mask some foreground object of image, we can not expect the network to reproduce the foreground objects from the umasked background. So we let the GAN loss to constrain the generation of masked region solely.

**Comment by LanTianBy** [comment]
> Firstly, calculates the L1 loss for unmasked region can promote the generated images preserving the unmasked content. Secondly, we may not expect the inpainted image to reproduce the content within the masked regions, for example, when we mask some foreground object of image, we can not expect the network to reproduce the foreground objects from the umasked background. So we let the GAN loss to constrain the generation of masked region solely.

Clear answer, thank you!
