### ISSUE TITLE
  What is the purpose of load_masked_position_encoding? What impact will it have on the outcome?

### ISSUE THREAD

**Issue by bigmover** [DQiaole/ZITS_inpainting#83]
https://github.com/DQiaole/ZITS_inpainting/blob/main/single_image_test.py#L132
![image](https://github.com/user-attachments/assets/f5dd8d79-48a5-4f65-9e2d-17bb879dc82d)

**Comment by DQiaole** [comment]
provide position information about the mask region. For the impact, plz refer to our paper.

**Comment by bigmover** [comment]
> provide position information about the mask region. For the impact, plz refer to our paper.

Thank you very much for your reply
