### ISSUE TITLE
How to make the Umsampling model?

### ISSUE THREAD

**Issue by naoki7090624** [DQiaole/ZITS_inpainting#9]
Thank you for sharing your great work!!

I try to train the network from scratch.
``TSR_train.py`` created ``best.pth``, ``latest.pth`` and ``log.txt`` in the ckpt directory. After that, I try to run the ```FTR_train.py```, but there is a error.
``FileNotFoundError: [Errno 2] No such file or directory: './ckpt/StructureUpsampling.pth'``

How to make the Upsampling model?

**Comment by ewrfcas** [comment]
It can be trained with a simple CNN as discussed in the paper sec.3.2. These training codes are not ready, but we have uploaded trained  StructureUpsampling.pth  (a very little CNN model) here. https://drive.google.com/drive/folders/1Dg_6ZCAi0U3HzrYgXwr9nSaOLnPsf9n-

**Comment by naoki7090624** [comment]
Will that pretrained model work correctly in another domain such as painting? Are you going to release these training code?

**Comment by ewrfcas** [comment]
Hi, here are the training codes.
https://github.com/ewrfcas/StructureUpsampling.
I think such a simple network can only work for edges that are slim as canny edges or lines.
